- name: update homebrew
  community.general.homebrew:
    name:
      - ansible
      - mas
      - git
      - jq
      - tree
      - wget
      - zsh
      - bun
      - nodebrew
      - pyenv
      - act
      - awscli
      - ffmpeg
      - gh
      - go
      - htop
      - lefthook
      - poetry
      - rbenv
      - rust
      - uv
