- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - discord
      - docker
      - google-chrome
      - ngrok
      - notion
      - postman
      - visual-studio-code
      - zoom
