- name: create /usr/local/cli-plugins for docker
  file:
    path: /usr/local/cli-plugins
    state: directory
    mode: '0755'
  become: true

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - 1password
    - claude
    - cmux
    - discord
    - docker
    - docker-desktop
    - drawio
    - fork
    - google-chrome
    - jetbrains-toolbox
    - libreoffice
    - lm-studio
    - microsoft-office
    - ngrok
    - parallels
    - postman
    - raycast
    - screen-studio
    - slack
    - splashtop-personal
    - visual-studio-code
    - voicepeak
    - zoom
  register: result
  failed_when:
    - result.failed
    - "'already an App at' not in result.msg"
